name: app_center_analytics
description: Visual Studio App Center (Analytics) plugin for Flutter applications.
version: 0.3.0
authors: 
  - Aloïs Deniel<alois.deniel@outlook.com>
  - Damien Aicheh<damien.aicheh@gmail.com>
homepage: https://github.com/aloisdeniel/flutter_plugin_appcenter

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"
  
dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.aloisdeniel.flutter.app_center_analytics
    pluginClass: AppcenterAnalyticsPlugin