name: appcenter_example
description: Demonstrates how to use the appcenter plugin.

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  app_center:
    path: ../src/app_center

  app_center_analytics:
    path: ../src/app_center_analytics

  app_center_crashes:
    path: ../src/app_center_crashes

flutter:
  uses-material-design: true
